version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password  # Change the password as needed
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"  # Neo4j Browser GUI
      - "7687:7687"  # Bolt protocol for database access
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
      - neo4j_import:/var/lib/neo4j/import

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_import:
